# orders-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: orders
spec:
  selector:
    app: orders
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
